In [3]:
import pandas as pd

In [4]:
emails_df = pd.read_csv('../data/emails_handled_missing.csv')
emails_df.head(5)

,Message-ID,Date,From,To,Subject,Mime-Version,Content-Type,Content-Transfer-Encoding,X-From,X-To,X-Folder,X-Origin,X-FileName,Message-Body
0,18782981.1075855378110.JavaMail.evans@thyme,"Mon, 14 May 2001 16:39:00 -0700 (PDT)",phillip.allen@enron.com,tim.belden@enron.com,NaN,1.0,text/plain; charset=us-ascii,7bit,Phillip K Allen,Tim Belden <Tim Belden/Enron@EnronXGate>,"\Phillip_Allen_Jan2002_1\Allen, Phillip K.\'Se...",Allen-P,pallen (Non-Privileged).pst,Here is our forecast\n\n
1,15464986.1075855378456.JavaMail.evans@thyme,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",phillip.allen@enron.com,john.lavorato@enron.com,Re:,1.0,text/plain; charset=us-ascii,7bit,Phillip K Allen,John J Lavorato <John J Lavorato/ENRON@enronXg...,"\Phillip_Allen_Jan2002_1\Allen, Phillip K.\'Se...",Allen-P,pallen (Non-Privileged).pst,Traveling to have a business meeting takes the...
2,24216240.1075855687451.JavaMail.evans@thyme,"Wed, 18 Oct 2000 03:00:00 -0700 (PDT)",phillip.allen@enron.com,leah.arsdall@enron.com,Re: test,1.0,text/plain; charset=us-ascii,7bit,Phillip K Allen,Leah Van Arsdall,\Phillip_Allen_Dec2000\Notes Folders\'sent mail,Allen-P,pallen.nsf,test successful. way to go!!!
3,13505866.1075863688222.JavaMail.evans@thyme,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",phillip.allen@enron.com,randall.gay@enron.com,NaN,1.0,text/plain; charset=us-ascii,7bit,Phillip K Allen,Randall L Gay,\Phillip_Allen_Dec2000\Notes Folders\'sent mail,Allen-P,pallen.nsf,"Randy,\n\n Can you send me a schedule of the s..."
4,30922949.1075863688243.JavaMail.evans@thyme,"Thu, 31 Aug 2000 05:07:00 -0700 (PDT)",phillip.allen@enron.com,greg.piper@enron.com,Re: Hello,1.0,text/plain; charset=us-ascii,7bit,Phillip K Allen,Greg Piper,\Phillip_Allen_Dec2000\Notes Folders\'sent mail,Allen-P,pallen.nsf,Let's shoot for Tuesday at 11:45.

In [5]:
emails_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495554 entries, 0 to 495553
Data columns (total 14 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Message-ID                 495554 non-null  object
 1   Date                       495554 non-null  object
 2   From                       495554 non-null  object
 3   To                         495554 non-null  object
 4   Subject                    478886 non-null  object
 5   Mime-Version               495554 non-null  float64
 6   Content-Type               495554 non-null  object
 7   Content-Transfer-Encoding  495554 non-null  object
 8   X-From                     495554 non-null  object
 9   X-To                       495554 non-null  object
 10  X-Folder                   495554 non-null  object
 11  X-Origin                   495554 non-null  object
 12  X-FileName                 495007 non-null  object
 13  Message-Body               495553 non-null  object
dtypes: float64(1), object(13)
memory usage: 52.9+ MB

In [6]:
emails_df.describe(include='object').T

,count,unique,top,freq
Message-ID,495554,495554,18782981.1075855378110.JavaMail.evans@thyme,1
Date,495554,217515,"Mon, 31 Dec 1979 16:00:00 -0800 (PST)",316
From,495554,19752,kay.mann@enron.com,16721
To,495554,58563,pete.davis@enron.com,9155
Subject,478886,169506,RE:,6162
Content-Type,495554,2,text/plain; charset=us-ascii,460945
Content-Transfer-Encoding,495554,29666,7bit,350955
X-From,495554,26891,Kay Mann,16314
X-To,495554,72027,pete.davis@enron.com,5334
X-Folder,495554,5127,\Kay_Mann_June2001_1\Notes Folders\All documents,6623
X-Origin,495554,259,Kaminski-V,26409
X-FileName,495007,3520,vkamins.nsf,23568
Message-Body,495553,241201,We've updated the Merger Q&A document on our E...,110