In [245]:
import pandas as pd
import numpy as np
import re

In [246]:
emails_df = pd.read_csv('../data/02_cleaned_emails_unlabelled_internal.csv')
emails_df.head()

,Date,From,To,Subject,X_From,X_To,Message,DISC,Entire-Message
0,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",phillip.allen@enron.com,john.lavorato@enron.com,Re:,Phillip K Allen,John J Lavorato <John J Lavorato/ENRON@enronXg...,Traveling to have a business meeting takes the...,NaN,Re: Traveling to have a business meeting takes...
1,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",phillip.allen@enron.com,randall.gay@enron.com,No Subject,Phillip K Allen,Randall L Gay,"Randy,\n Can you send me a schedule of the sal...",NaN,"No Subject Randy,\n Can you send me a schedule..."
2,"Tue, 22 Aug 2000 07:44:00 -0700 (PDT)",phillip.allen@enron.com,"david.l.johnson@enron.com, john.shafer@enron.com",No Subject,Phillip K Allen,"david.l.johnson@enron.com, John Shafer",Please cc the following distribution list with...,NaN,No Subject Please cc the following distributio...
3,"Mon, 16 Oct 2000 06:42:00 -0700 (PDT)",phillip.allen@enron.com,buck.buckner@honeywell.com,Re: FW: fixed forward or other Collar floor ga...,Phillip K Allen,"""Buckner, Buck"" <buck.buckner@honeywell.com> @...","Mr. Buckner,\n For delivered gas behind San Di...",NaN,Re: FW: fixed forward or other Collar floor ga...
4,"Fri, 13 Oct 2000 06:45:00 -0700 (PDT)",phillip.allen@enron.com,stagecoachmama@hotmail.com,No Subject,Phillip K Allen,stagecoachmama@hotmail.com,"Lucy,\n Here are the rentrolls:\n Open them an...",NaN,"No Subject Lucy,\n Here are the rentrolls:\n O..."

In [247]:
emails_df.columns

Index(['Date', 'From', 'To', 'Subject', 'X_From', 'X_To', 'Message', 'DISC',
       'Entire-Message'],
      dtype='object')

In [248]:
emails_df_msg_label = emails_df.drop(columns=['X_From', 'X_To', 'Date', 'From', 'To', 'Subject', 'Message'])
emails_df_msg_label.head()

   DISC                                     Entire-Message
0   NaN  Re: Traveling to have a business meeting takes...
1   NaN  No Subject Randy,\n Can you send me a schedule...
2   NaN  No Subject Please cc the following distributio...
3   NaN  Re: FW: fixed forward or other Collar floor ga...
4   NaN  No Subject Lucy,\n Here are the rentrolls:\n O...

In [249]:
emails_df_rule_based = emails_df_msg_label.sample(5000, random_state=32).copy()
rule_based_ids = emails_df_rule_based.index.tolist()
print(rule_based_ids)

[34304, 29217, 30268, 32821, 10558, 18577, 26404, 63883, 1235, 26667, 7284, 58029, 15554, 17459, 58940, 30565, 37824, 56941, 34539, 57314, 15526, 25263, 30286, 63763, 29448, 64255, 62413, 47079, 48610, 3027, 13492, 58812, 32049, 21449, 45526, 28446, 56265, 46566, 16184, 14531, 10943, 40511, 15141, 27351, 3789, 37116, 36605, 18516, 27655, 46056, 51221, 4431, 21830, 26947, 34993, 61532, 4268, 62367, 28492, 16010, 41793, 8444, 6417, 62051, 27409, 35985, 18099, 14411, 62732, 33813, 54143, 23637, 8800, 15495, 36834, 52964, 27758, 10918, 15477, 4655, 16365, 29677, 11709, 64101, 15488, 41965, 13054, 28529, 24916, 14821, 60370, 55866, 30514, 8065, 45326, 21784, 61759, 55631, 25272, 48115, 36277, 44948, 11708, 37553, 10871, 26538, 17409, 52922, 40673, 60271, 46272, 25940, 63098, 51715, 5655, 26083, 33602, 12284, 39936, 63805, 4184, 4590, 11631, 63235, 12551, 5656, 64299, 13420, 40680, 46930, 39999, 15995, 61207, 64662, 25398, 36910, 5542, 39823, 31684, 63704, 8705, 44818, 55998, 22538, 27497, 9032, 21586, 2831, 52592, 45327, 39671, 7638, 36916, 37649, 47954, 43412, 29547, 15027, 30233, 52183, 16766, 58349, 37699, 17903, 33292, 37973, 30050, 50981, 47136, 54164, 35333, 63064, 62653, 50606, 49601, 40778, 122, 3716, 55996, 46795, 2609, 56637, 50088, 28151, 36339, 1960, 37481, 2582, 55227, 14242, 17411, 12553, 37761, 52285, 27126, 25079, 12238, 51184, 61634, 60555, 24815, 22873, 15719, 52644, 11973, 58599, 21878, 10348, 45207, 51810, 34270, 24471, 32994, 7821, 5525, 4233, 4160, 64210, 2710, 49477, 40989, 5050, 60013, 63992, 21003, 4125, 40018, 55704, 2422, 39502, 24800, 27827, 30703, 45387, 8135, 6827, 42876, 38282, 54072, 17370, 8850, 10006, 11988, 63156, 37034, 29196, 25429, 58327, 31686, 56133, 48877, 28447, 52241, 4346, 13271, 55888, 43520, 63304, 24448, 56470, 50684, 4039, 40843, 32767, 44698, 16926, 54650, 31986, 38853, 7613, 60832, 5273, 52509, 51800, 3983, 27287, 48960, 13157, 56031, 18949, 10776, 25701, 57359, 37174, 58633, 3637, 31279, 31734, 32066, 2763, 40690, 12158, 29314, 22047, 36887, 31347, 2197, 47413, 40222, 26041, 49879, 65374, 38498, 46607, 61235, 49665, 20067, 32756, 65308, 57194, 54603, 27046, 54239, 61712, 56543, 14680, 28701, 23564, 61803, 42376, 60163, 15121, 1006, 40211, 23327, 64924, 33971, 43993, 17722, 18446, 21682, 62671, 26061, 59345, 6949, 7303, 4878, 56244, 18123, 43971, 44505, 29747, 57519, 33678, 9351, 47373, 63535, 37279, 59551, 40446, 28542, 7664, 43731, 27292, 54063, 47415, 4473, 329, 46922, 20182, 12479, 43461, 60117, 63547, 57962, 34278, 34415, 8704, 59733, 38211, 54154, 40240, 51908, 28727, 11671, 29051, 23856, 17127, 55077, 17493, 29618, 6931, 654, 13920, 50478, 11696, 30742, 40450, 8894, 22970, 50602, 33847, 57096, 36440, 48946, 29138, 30621, 16450, 25394, 55292, 43660, 26, 52595, 42982, 45517, 55580, 3801, 19723, 37526, 54849, 59928, 26067, 54138, 36753, 20779, 51193, 23040, 44678, 35502, 53252, 30072, 21954, 19124, 43036, 27100, 61778, 32695, 29713, 50653, 33625, 23251, 985, 42647, 13980, 44522, 49012, 2200, 22415, 63188, 6828, 40617, 46923, 39350, 61949, 25111, 18853, 6588, 39200, 38656, 17327, 24169, 34962, 17623, 29838, 56736, 45456, 59814, 16984, 29192, 6677, 43728, 899, 24939, 13904, 15909, 16057, 17984, 12826, 15607, 34694, 39815, 14965, 52943, 14153, 47185, 24496, 38614, 5262, 34074, 27810, 128, 56207, 50569, 16037, 17772, 6498, 45030, 62105, 50881, 34742, 52130, 33485, 20597, 48658, 6418, 18183, 8819, 35145, 39457, 31252, 63455, 6034, 17614, 61201, 1859, 57908, 33225, 20082, 31895, 60543, 32552, 65360, 47107, 23607, 232, 49183, 22888, 10371, 42548, 25702, 63862, 9959, 17472, 44715, 6044, 32907, 38355, 58939, 12614, 53996, 53277, 48763, 1233, 54962, 32089, 59968, 16850, 3918, 911, 18225, 47739, 24473, 49864, 40150, 31819, 52903, 55963, 60545, 50608, 10601, 24770, 5956, 43676, 60801, 56349, 51643, 10826, 32324, 22694, 60886, 64816, 34397, 44883, 10789, 46122, 36687, 30131, 48597, 53360, 30622, 35388, 53197, 40885, 12358, 3350, 57852, 28169, 24749, 52699, 29331, 8369, 26291, 64622, 18455, 5053, 39966, 29973, 39056, 29914, 11147, 50872, 20420, 50965, 11667, 4589, 40487, 38925, 18025, 55300, 9366, 63742, 55462, 50793, 28459, 60541, 3128, 42754, 7471, 1952, 3903, 36269, 56100, 13583, 55725, 41860, 3790, 36479, 40388, 13428, 3873, 14429, 17696, 28980, 24537, 23721, 5661, 26004, 7305, 23671, 29617, 49217, 6460, 53430, 22369, 4847, 18840, 39788, 9313, 34534, 7631, 11234, 38, 57538, 7905, 48086, 36934, 8074, 45906, 4781, 14845, 6970, 38340, 8298, 34994, 39906, 53935, 34937, 53795, 8992, 36601, 21309, 59522, 23447, 1316, 55419, 51024, 26165, 48134, 10286, 35200, 5320, 7498, 23079, 28674, 47703, 11776, 25403, 532, 30739, 5001, 47489, 65470, 46959, 3378, 21919, 53599, 38725, 24407, 23723, 28830, 41917, 33800, 21426, 3516, 18607, 2298, 4495, 16952, 58468, 20459, 61636, 52168, 16168, 23970, 55616, 47294, 34111, 10021, 19978, 118, 64614, 63122, 36642, 4865, 26799, 64633, 15886, 607, 18224, 17856, 41601, 35031, 7089, 2011, 30991, 60693, 49114, 29048, 40436, 17930, 20230, 28899, 62329, 55694, 52845, 23074, 30003, 16428, 1803, 40022, 6627, 54772, 59030, 10136, 16280, 35260, 42752, 39066, 18833, 18186, 37760, 49633, 63559, 5857, 35088, 10256, 17429, 61255, 10116, 39187, 53590, 26233, 34777, 3901, 22211, 15772, 61294, 54491, 16997, 50058, 25122, 45371, 65460, 21500, 54328, 11820, 32670, 62474, 9061, 55848, 24648, 35314, 64847, 43445, 7533, 49846, 43163, 55536, 55060, 1910, 38915, 57195, 37764, 11550, 58864, 40160, 20463, 35835, 43192, 57052, 11141, 34051, 58762, 61274, 26980, 1082, 56350, 19970, 33639, 45986, 24349, 8872, 13560, 48440, 24057, 10023, 27026, 6572, 62050, 15095, 63795, 41795, 24621, 19031, 27090, 62034, 9918, 8206, 2565, 11714, 59617, 46662, 24354, 63039, 18430, 59269, 52235, 21123, 41683, 13318, 42199, 31780, 19604, 53085, 7489, 22337, 35247, 39, 47316, 12272, 63299, 6511, 29627, 28557, 41708, 39879, 53191, 22932, 57355, 21518, 56008, 51229, 17009, 44692, 8312, 48790, 39032, 56818, 55660, 53177, 2135, 9548, 12251, 4718, 53793, 33937, 19516, 48129, 37984, 56383, 43313, 33794, 25179, 50028, 1747, 5940, 31386, 58641, 34033, 8411, 5395, 31977, 53748, 37435, 42957, 32160, 62165, 41438, 52962, 59174, 56711, 48795, 23300, 25688, 38897, 32351, 60783, 63399, 26789, 59013, 5381, 9049, 53818, 35341, 64030, 13418, 2028, 65000, 28440, 45958, 6313, 33386, 3226, 47817, 9833, 27978, 57671, 5950, 55796, 24501, 38495, 40603, 47869, 13034, 8416, 27734, 14305, 23185, 11390, 53532, 50966, 59016, 60472, 50492, 24009, 9263, 65480, 26560, 92, 1228, 41008, 18553, 56538, 57439, 40978, 48200, 30826, 36863, 28526, 43169, 26529, 10888, 24752, 46455, 2470, 42525, 25156, 20947, 54511, 56645, 32731, 35871, 62551, 61833, 18925, 49969, 58989, 45339, 54478, 16722, 60765, 32538, 59012, 13884, 56540, 37125, 22965, 52353, 12492, 31178, 7560, 27804, 38122, 18772, 61555, 51925, 44263, 53462, 56255, 30015, 60883, 6271, 2249, 62102, 51719, 1161, 43605, 7887, 16928, 19637, 49663, 34967, 61999, 61112, 59871, 22535, 2628, 64751, 4722, 38827, 50462, 18584, 35884, 61631, 23424, 56110, 46854, 31610, 34772, 26155, 4961, 41325, 39422, 57503, 61747, 1500, 13928, 42214, 43006, 11876, 42231, 32741, 39520, 6296, 1175, 33864, 63170, 46104, 57951, 56346, 31187, 28376, 44907, 35858, 64761, 57784, 25110, 5552, 3463, 51791, 41171, 3211, 64968, 6280, 38682, 2105, 5526, 9877, 1884, 47619, 35061, 13260, 8018, 42026, 36324, 45008, 52288, 48349, 44458, 53940, 34236, 54218, 8769, 22023, 60088, 36648, 62451, 32339, 10066, 28255, 51254, 57837, 16376, 56714, 6633, 45164, 62632, 23628, 35613, 59509, 10952, 63555, 45758, 9561, 22117, 63662, 43411, 25102, 19757, 25305, 17149, 46313, 30795, 54041, 29193, 38168, 42136, 5693, 6457, 28240, 28689, 37768, 32928, 55950, 3198, 45328, 49573, 14162, 25952, 2454, 53448, 26615, 31646, 13577, 46364, 37328, 61990, 48262, 13479, 54752, 62113, 58158, 24764, 18095, 63513, 668, 26694, 23099, 26448, 25552, 1355, 26128, 64380, 51044, 37532, 48570, 6990, 42253, 20383, 9432, 24021, 6769, 7735, 50481, 5375, 11724, 60645, 9218, 8650, 52144, 30235, 6060, 27445, 47256, 17708, 58218, 58525, 34070, 48040, 15661, 29911, 40077, 15507, 53928, 3284, 62851, 38368, 37451, 3486, 64594, 22957, 1248, 65232, 30062, 40582, 51524, 36890, 15470, 61000, 21562, 47329, 11676, 9212, 55839, 25499, 18037, 14853, 39446, 57333, 29366, 15939, 24276, 25989, 4992, 26766, 43879, 19417, 7435, 293, 44572, 23756, 63617, 566, 30881, 46784, 43826, 24430, 8296, 6877, 9219, 55432, 46110, 21314, 55639, 37267, 25297, 6629, 6279, 59685, 34207, 20118, 51159, 27861, 9553, 22987, 5710, 26510, 24997, 36329, 48321, 60373, 4864, 17729, 14517, 45408, 46498, 57225, 22169, 64482, 59775, 25072, 54918, 20513, 7214, 61361, 12534, 26020, 33148, 7952, 59147, 22252, 5308, 33790, 49636, 20263, 17042, 10343, 43661, 27924, 30389, 27673, 38003, 55490, 20119, 27838, 52088, 63279, 29909, 24882, 35993, 52485, 38825, 47997, 60510, 8691, 10849, 31757, 23096, 60103, 36263, 2415, 38587, 24475, 37845, 18879, 42938, 57682, 44695, 19322, 43080, 28991, 42111, 48380, 36615, 27089, 7947, 42480, 28660, 25432, 12419, 33702, 20359, 17481, 56557, 46932, 18233, 6909, 36365, 50313, 25321, 33327, 1769, 1468, 59328, 47690, 2737, 28722, 22860, 27878, 31538, 16818, 8139, 12132, 2201, 25175, 28519, 3853, 11692, 61591, 8745, 30790, 54351, 63928, 1213, 21489, 32336, 9167, 5173, 64325, 4578, 63780, 62741, 59801, 3871, 10250, 57382, 14177, 38467, 54520, 53972, 35265, 31660, 17016, 9979, 37769, 37667, 16395, 63785, 46024, 1508, 6793, 22463, 34134, 42976, 7238, 44313, 50683, 26462, 51240, 47534, 61451, 15216, 42198, 48774, 36271, 43747, 47800, 58533, 12468, 24406, 1112, 28391, 43376, 36467, 55194, 48876, 15454, 3671, 50982, 45846, 41644, 23000, 18523, 4657, 57256, 5488, 4190, 63927, 34912, 28896, 37196, 34687, 32654, 47989, 59517, 12089, 22984, 33227, 39708, 52646, 63127, 18333, 37744, 12106, 41175, 44194, 41379, 46722, 34342, 50447, 54970, 8150, 48365, 63282, 7006, 10881, 1398, 37456, 3976, 22839, 42140, 52576, 52243, 2123, 62845, 55527, 44386, 53044, 28978, 16742, 12729, 17495, 46396, 40095, 14625, 43174, 19687, 59728, 46982, 14559, 46726, 50549, 8316, 13405, 15073, 59582, 57391, 9732, 21983, 28798, 37420, 50490, 35601, 13534, 54704, 58679, 48317, 16555, 37158, 16196, 50037, 28621, 32999, 30001, 43424, 23254, 19960, 19156, 21080, 40971, 35762, 34440, 47348, 6288, 59988, 37322, 27677, 56692, 18149, 32683, 13997, 32609, 63804, 46013, 37170, 1576, 54868, 39120, 12153, 33178, 41335, 58526, 4132, 46461, 45023, 6483, 41309, 8725, 31201, 9644, 57732, 47631, 55743, 33848, 27763, 20036, 30053, 41276, 20885, 13292, 13771, 55399, 63214, 47002, 53846, 5492, 26171, 32710, 42550, 9312, 48854, 41165, 10097, 19870, 53528, 52180, 37448, 38485, 26677, 46438, 5127, 5394, 35101, 48799, 36154, 3200, 28301, 43910, 10628, 5520, 45155, 30249, 27613, 32516, 3897, 53166, 50319, 33168, 62258, 26100, 39528, 32563, 64856, 62933, 45103, 30327, 60031, 46205, 59803, 7115, 20543, 59130, 61533, 61593, 24673, 29325, 44811, 29282, 7363, 38914, 5237, 41868, 38028, 44155, 43201, 46787, 7018, 46137, 17758, 54371, 21667, 53847, 8188, 20729, 35577, 54012, 1866, 14840, 10977, 29016, 13300, 53481, 14379, 56131, 33614, 42750, 2363, 28455, 30734, 30042, 24045, 42924, 47009, 33069, 41530, 61720, 29495, 34620, 22583, 59755, 29078, 30297, 56143, 4537, 30562, 23346, 21635, 38718, 51882, 28705, 43046, 2349, 46651, 48933, 21347, 9492, 46229, 24885, 27038, 2697, 40415, 46800, 4341, 41219, 48750, 36451, 61359, 13385, 9138, 46641, 770, 2364, 19724, 55781, 61911, 46431, 20626, 4908, 20934, 57208, 10239, 7923, 49329, 17554, 53428, 23209, 27346, 32233, 39853, 11007, 58848, 17549, 27294, 36626, 8798, 62910, 56509, 38951, 41251, 49182, 14995, 64988, 24000, 46565, 6461, 45566, 16595, 21643, 59435, 7589, 38574, 65236, 2168, 35094, 6654, 49561, 21669, 24575, 6007, 26796, 35954, 1127, 39059, 12133, 37156, 56490, 891, 12366, 43596, 26863, 44958, 35987, 16337, 21043, 52245, 11609, 56392, 35582, 18434, 58752, 33204, 36984, 62686, 63703, 23604, 40162, 4592, 59459, 30827, 25325, 22161, 42861, 27587, 8736, 27047, 9695, 60640, 49404, 8877, 30037, 30205, 60238, 42723, 21648, 33665, 9727, 19387, 2731, 55610, 52236, 21762, 38443, 32277, 25441, 997, 31721, 35734, 9578, 50346, 24696, 13906, 17439, 33051, 56179, 31644, 40931, 4200, 15225, 45308, 26199, 36891, 56394, 18322, 27361, 48558, 7527, 40339, 41656, 13312, 51691, 62507, 2442, 50332, 12103, 5836, 32005, 376, 21597, 41157, 12769, 57023, 40440, 25777, 51238, 43760, 6011, 28415, 11897, 48471, 60763, 29985, 21639, 53492, 57581, 26318, 40257, 54120, 14640, 47181, 4252, 47769, 2144, 41635, 21131, 55446, 34061, 49966, 52315, 46010, 3426, 24570, 59986, 22632, 38451, 31221, 64780, 57591, 28873, 40518, 50271, 13362, 58333, 37679, 22331, 28123, 45021, 59031, 30013, 9751, 64321, 59372, 71, 58360, 64993, 14877, 39152, 53654, 65251, 25784, 4994, 2344, 49244, 43109, 17949, 23428, 49193, 52213, 36315, 4602, 60660, 53682, 35711, 45115, 42440, 32012, 1795, 35397, 20639, 9175, 41538, 36453, 22983, 27253, 49006, 13863, 58072, 14599, 14249, 56209, 25560, 56707, 39313, 13998, 62320, 9963, 39464, 36544, 58686, 58112, 7932, 1571, 18626, 52630, 18968, 57120, 56717, 34523, 41095, 18217, 58180, 35650, 35421, 17657, 25550, 16684, 40134, 3522, 6525, 32742, 38695, 22128, 35996, 37800, 59018, 53772, 34738, 40435, 15544, 38339, 38275, 24802, 55277, 10151, 2909, 22675, 8092, 42364, 58392, 51503, 40396, 37427, 43543, 64717, 13056, 49313, 54034, 5851, 44104, 45014, 64740, 20587, 59110, 34537, 6023, 31759, 19497, 21040, 36729, 2550, 19216, 26287, 63414, 46152, 39429, 29786, 1881, 16460, 55981, 52623, 23735, 30281, 4848, 26206, 57843, 57789, 40118, 55488, 4768, 8814, 2320, 53500, 43118, 41285, 32913, 202, 40494, 62630, 19695, 7889, 47672, 43098, 44293, 5432, 59680, 33408, 32993, 21955, 18483, 59230, 11229, 32565, 50529, 38531, 28095, 37979, 31218, 17487, 14520, 35407, 44697, 39922, 58309, 37654, 27233, 7618, 3376, 23307, 239, 50280, 17036, 20715, 56857, 5763, 11417, 36416, 47070, 8873, 19786, 38910, 2675, 51013, 49044, 39687, 5944, 7720, 10738, 1985, 44960, 54566, 55458, 8730, 17655, 37221, 1799, 41454, 27881, 64811, 29552, 16856, 24340, 38906, 24632, 60864, 11450, 43187, 59126, 18622, 42541, 5826, 38838, 42832, 908, 12797, 14752, 44230, 21122, 25774, 2157, 34464, 45197, 34244, 2469, 29961, 23947, 45757, 37004, 32381, 38178, 55209, 49671, 9713, 29097, 23633, 5724, 7068, 47699, 13334, 63010, 5048, 29591, 49898, 39411, 46529, 31816, 47476, 45645, 21073, 10522, 32951, 23911, 60343, 41358, 6524, 27101, 5622, 831, 8302, 43056, 14820, 58811, 2346, 63624, 31292, 39532, 6988, 57609, 9716, 49518, 6846, 42186, 34216, 13415, 64272, 55760, 64624, 43761, 23263, 46370, 26734, 53796, 9666, 14900, 8637, 51482, 24619, 27230, 46269, 19158, 33487, 54235, 57511, 53607, 58639, 6776, 47555, 46835, 44929, 3411, 62998, 6395, 13952, 6815, 37691, 38858, 50895, 13216, 47589, 16201, 3275, 63032, 62482, 20598, 16491, 19785, 27140, 16156, 2834, 29966, 65250, 51816, 64463, 23888, 60565, 33271, 588, 40019, 7876, 58346, 52461, 30865, 10629, 13379, 41493, 20052, 43552, 47225, 58629, 34579, 61370, 7187, 11083, 63439, 33246, 57040, 48118, 44610, 26975, 19121, 17606, 25348, 64793, 42356, 41100, 33434, 32909, 25629, 45474, 43312, 45702, 59400, 49551, 42573, 42404, 10669, 44546, 30955, 65301, 33166, 41316, 24365, 16999, 57811, 53045, 55524, 34774, 32580, 54038, 9301, 57915, 40427, 6046, 24082, 52167, 31611, 21731, 24350, 26324, 47363, 33058, 61828, 11429, 56387, 28072, 27868, 64682, 57901, 4538, 1404, 2027, 51727, 19895, 19578, 27609, 30823, 18994, 19010, 35282, 2189, 48769, 56626, 65058, 35572, 38857, 17617, 37087, 24079, 44333, 58269, 2259, 63809, 47592, 17005, 36335, 23619, 42034, 38636, 37395, 48579, 6107, 14073, 35991, 6230, 57344, 14184, 64544, 52959, 15612, 57946, 4756, 13842, 55035, 14959, 17126, 21558, 46946, 25458, 12870, 63695, 46263, 15996, 51758, 26438, 49262, 5120, 1842, 35, 11465, 51144, 36791, 29070, 24713, 7371, 44743, 17011, 59162, 48082, 31026, 16522, 34946, 14702, 6322, 55768, 2946, 33646, 18200, 51747, 14929, 33673, 48962, 49610, 49991, 65314, 62389, 33612, 21224, 48589, 23270, 52982, 52345, 1306, 53851, 7083, 48449, 19753, 47969, 25180, 11492, 7755, 12126, 19760, 56245, 62135, 1250, 3860, 58521, 24772, 12985, 38883, 20325, 45010, 59042, 30848, 2070, 37623, 65205, 63079, 12035, 21632, 25438, 47096, 28429, 5478, 36865, 64753, 39977, 58621, 4767, 19297, 59670, 13829, 11018, 1661, 41856, 20798, 2471, 51137, 228, 21237, 39979, 3566, 45814, 20884, 9088, 54058, 35462, 48406, 30406, 41997, 18680, 55436, 4695, 61656, 49442, 13227, 36456, 22759, 35443, 34297, 1832, 16980, 24817, 52976, 3477, 27390, 5670, 42115, 8, 48128, 53604, 8761, 9286, 41721, 15485, 35643, 46193, 19055, 37740, 13967, 30251, 65333, 37621, 61816, 48594, 31579, 18243, 10421, 32136, 63264, 4562, 31607, 47204, 34231, 28806, 45261, 3614, 49127, 55895, 9035, 56480, 14617, 12912, 17952, 53832, 13244, 53651, 41945, 33640, 40380, 3410, 52591, 31236, 57798, 28527, 24381, 42338, 55953, 30034, 51793, 61030, 43963, 59101, 6690, 28285, 29189, 54974, 63764, 28258, 12050, 40822, 2548, 28484, 40943, 1288, 64340, 10029, 23538, 4575, 32575, 8504, 52272, 54537, 17896, 49453, 14644, 48433, 52543, 55612, 40227, 25138, 52486, 8672, 36153, 62382, 40155, 62156, 23394, 39345, 63391, 25069, 12865, 37351, 6768, 14467, 39859, 43884, 58370, 21296, 39133, 54517, 28565, 7251, 42979, 40853, 15015, 29997, 19471, 8762, 38717, 49134, 20736, 3283, 34715, 34516, 53108, 27782, 10633, 32725, 46430, 37302, 46883, 27599, 29413, 24421, 16880, 8775, 15479, 21815, 11471, 52866, 11846, 23606, 55892, 13734, 33137, 53475, 22806, 15000, 13671, 63642, 62844, 14333, 61812, 1986, 35776, 17535, 30114, 14705, 35125, 22040, 31446, 15797, 51110, 1345, 54308, 48909, 29342, 22317, 9512, 57103, 44493, 31059, 25915, 40510, 37096, 3482, 31425, 59184, 31589, 56907, 34951, 34953, 39416, 17519, 18142, 35037, 19022, 19345, 19896, 50747, 1501, 57485, 22060, 40858, 63259, 42379, 34725, 13580, 36129, 11816, 28828, 25729, 1670, 10831, 77, 38057, 61535, 43431, 11473, 29161, 33457, 44971, 57696, 47141, 14419, 22784, 7977, 24480, 16276, 8360, 1553, 58200, 29482, 59202, 3049, 9507, 42684, 35840, 55428, 29388, 38878, 59226, 45482, 20604, 5591, 35535, 24064, 54464, 63249, 29899, 53408, 25624, 13455, 3988, 42884, 12762, 25997, 20334, 15105, 45450, 16047, 43053, 35280, 15264, 17047, 55664, 7013, 61144, 21356, 23148, 53489, 12832, 59675, 58614, 62265, 37790, 26069, 12754, 44742, 9745, 44861, 37535, 47807, 43042, 46998, 25410, 33515, 8644, 10597, 36976, 1269, 44860, 52904, 51879, 61696, 5758, 2501, 4062, 21484, 255, 55730, 36268, 16640, 31122, 31530, 18767, 1556, 28847, 50832, 29802, 51025, 15697, 33867, 46936, 50746, 47409, 42227, 61581, 7701, 13896, 26754, 16404, 45337, 6162, 31501, 18296, 14210, 62123, 31509, 29013, 28931, 46064, 47364, 65399, 34755, 45379, 59819, 54402, 11058, 12726, 13018, 4867, 22126, 32518, 29508, 526, 19683, 8028, 20879, 3468, 49919, 43711, 6664, 27965, 27522, 42589, 22511, 37442, 61753, 21522, 59218, 36089, 27729, 20342, 20451, 54881, 21008, 44250, 30132, 61146, 58149, 56499, 14443, 31857, 682, 9615, 17388, 2005, 18634, 58553, 829, 37040, 11401, 31470, 38272, 23801, 24127, 36599, 10572, 20656, 25833, 45154, 44934, 5599, 11065, 41686, 59368, 12269, 1374, 64345, 11909, 45068, 30981, 57228, 33224, 37045, 47216, 8923, 63131, 5215, 28553, 13081, 56427, 21423, 1357, 59663, 49558, 45530, 56524, 37682, 40143, 22870, 45687, 15232, 24342, 18901, 40599, 45152, 20547, 19126, 21521, 28487, 9551, 53318, 57189, 57257, 47006, 39072, 50999, 72, 21186, 37849, 27821, 34844, 7262, 54358, 61134, 11703, 19954, 38119, 63973, 12461, 14488, 49635, 63471, 9534, 11128, 17813, 64586, 61836, 3685, 7828, 33694, 1732, 2224, 64315, 36289, 1424, 4249, 9192, 7542, 156, 5057, 45878, 11940, 51960, 21390, 57010, 44817, 41955, 17802, 27252, 23205, 25585, 64100, 22132, 55295, 23683, 42775, 28139, 52695, 23314, 17045, 59062, 34759, 9678, 60530, 47511, 20361, 30214, 13454, 13232, 47749, 28524, 33146, 5810, 30416, 19292, 63515, 3672, 28511, 54528, 64518, 62357, 63251, 38991, 6421, 44370, 33588, 62284, 43233, 420

In [250]:
# lowercasing and remove punctuation
PUNC_PATTERN = re.compile(r'[^\w\s]')

def preprocess_text_for_rule_based(text):
    if not isinstance(text, str):
        return ''


    text = PUNC_PATTERN.sub('', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip().lower()
    return text

emails_df_rule_based['Entire-Message'] = emails_df_rule_based['Entire-Message'].apply(preprocess_text_for_rule_based)
emails_df_rule_based.head()

       DISC                                     Entire-Message
34304   NaN  no subject jeff can you set up a meetin with y...
29217   NaN  re tom costantino ill set him up on an intervi...
30268   NaN  thursday staff meetings urgent hi everyone wit...
32821   NaN  letter to stephen baum re solicitation of empl...
10558   NaN  filings there were 3 puc filings mentioned in ...

In [251]:
DISC_KEYWORDS = {
    'D' : ["deadline", "urgent", "now", "action", "priority", "resolve", "results",
        "decision", "goal", "challenge", "do it", "fast", "push", "lead", "firm", "pressure", "action required",
        "quickly", "at all costs", "make it happen", "efficiently", "asap"
        "take the lead", "take action", "do it now", "get this done", "make sure",
        "ensure", "enforce", "absolutely", "direct", "right now", "immediately",
        "speed", "I want", "I said", "must",  "put questions to rest", "your fault",
        "your mistake", "your apologies", "your bad", "your error", "your oversight",
        "your slip", "your blunder", "your carelessness", "your inattention",
        "your neglect", "your omission", "your oversight", "I guarantee",
        "enough is enough", " you need to"],
    'I' : ["excited", "great job", "lets", "share", "appreciate",
        "celebrate", "fun", "engage", "collaborate", "believe",
          "nice to hear", "amazing", "awesome", "fantastic", "get a hold of me",
          "discuss", "chat", "jokes", "laugh", "smile", "happy", "good news", "favorite",
          "favourite", "celebrate", "congratulations", "kudos", "celebration", "party",
          "playing", "exciting", "thrilling", "enjoy", "game"],
    'S' : ["kindly", "let me know", "available", "cooperate", "help", "understand",
        "follow up", "consistent", "appreciate your help", "thanks again",
        "dont worry", "help in any way I can", "let me know", "comfortable",
        "sorry for not responding", "thank you so much", "my fault", "my mistake",
        "my apologies", "my bad", "my error", "my oversight", "my slip", "my blunder",
        "my carelessness", "my inattention", "my neglect", "my omission", "my oversight",
        "sorry", "apologize for", "agree"],
    'C' : ["details", "data", "report", "analyze", "summary", "document", "proof",
        "schedule", "spreadsheet", "accuracy", "format", "process", "standards", "analysis",
        "compliance", "audit", "method", "evidence", "confirm", "structured", "sources",
        "review", "check", "validate", "verify", "validate", "as per", "according to",
        "in accordance with", "consistent with", "comply with", "follow", "procedure",
        "guideline", "manual", "policy", "regulation", "rule", "standard", "statute",
        "requirement", "specification", "protocol", "principle", "reconcile", "cross-check",
        "cross-reference", "corroborate", "substantiate", "authenticate", "confirm", "justify",
        "hindsight", "forethought", "foresight", "insight", "formula", "unjustified",
        "unsubstantiated", "unverified", "unvalidated", "unconfirmed", "unjust", "unreasonable",
        "looking into", "investigate", "examine", "probe", "scrutinize", "inspect", "identified",
        "final execution", "implementation", "calculation", "agreement", "calibrate"]
}

In [ ]:
# def match_disc_label(msg):
#     disc_labels = set()
#     for label, keywords in DISC_KEYWORDS.items():
#         for word in keywords:
#             if word in msg:
#                 disc_labels.add(label)

#     return disc_labels

def match_disc_label(msg, max_freq=2):
    labels_freq = {'D': 0, 'I': 0, 'S': 0, 'C': 0}
    for label, keywords in DISC_KEYWORDS.items():
        for word in keywords:
            if word in msg:
                labels_freq[label] += 1
    # print(labels_freq)

    filter_labels = {label: freq for label, freq in labels_freq.items() if freq > 0}
    if not filter_labels:
        return ()

    sorted_labels_freq = sorted(filter_labels.items(), key=lambda x: (-x[1], x[0]))
    top_labels = [label for label, freq in sorted_labels_freq[:max_freq]]
    return tuple(top_labels)

emails_df_rule_based['DISC_rule_based'] = emails_df_rule_based['Entire-Message'].apply(match_disc_label)

print(emails_df_rule_based.head(5))
print(emails_df_rule_based['DISC_rule_based'].value_counts())

       DISC                                     Entire-Message DISC_rule_based
34304   NaN  no subject jeff can you set up a meetin with y...              ()
29217   NaN  re tom costantino ill set him up on an intervi...          (C, D)
30268   NaN  thursday staff meetings urgent hi everyone wit...          (C, D)
32821   NaN  letter to stephen baum re solicitation of empl...              ()
10558   NaN  filings there were 3 puc filings mentioned in ...            (C,)
DISC_rule_based
(C, D)    1183
()         627
(C,)       551
(C, S)     429
(C, I)     340
(D,)       286
(S, D)     264
(S, C)     264
(I,)       218
(D, I)     196
(D, C)     191
(D, S)     167
(S,)       109
(I, C)      65
(I, D)      50
(I, S)      46
(S, I)      14
Name: count, dtype: int64

In [ ]:
# emails_df_rule_based_none = emails_df_rule_based[emails_df_rule_based['DISC_rule_based'].apply(lambda x: len(x) == 0)]
# print(emails_df_rule_based_none['Entire-Message'])

# emails_df_rule_based_none.to_csv('../data/msg_without_labels.csv', index=False)
# print(emails_df_rule_based_none.value_counts())

34304    no subject jeff can you set up a meetin with y...
32821    letter to stephen baum re solicitation of empl...
1235     wednesdays swap meeting canceled tomorrows swa...
37824    when you are ready hey guys call me when you a...
47079    map ben in regards to the chicago area we also...
                               ...
40285    baseball stats we talked a couple of weeks ago...
12341    board meeting rick i need your view on which o...
15061    pirate cake can have a cake with rough blue ic...
55780    the newshour with jim lehrer sponsorship oppor...
126      no subject daryl here is the file that include...
Name: Entire-Message, Length: 627, dtype: object